Fix missing include + Makelfile
error: Kenrel Module Functions Undefined -> add vfs.h to Makefile
error: double declaration -> remove `int set_page_rw` & `int set_page_ro` from hijack.h and .c